### ISSUE TITLE
Sporadic test failure in authentication_spec

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-api#1101]
```
Failures:

  1) Authentication API Token Based Authentication when using a cache session store Tokens for Web Sockets gets a UI based token_ttl when requesting token for web sockets

     Failure/Error: expect(response.parsed_body["token_ttl"]).to eq(::Settings.session.timeout.to_i_with_method)
     
       expected: 3600
            got: nil
     
       (compared using ==)
     # ./spec/requests/authentication_spec.rb:371:in `block (6 levels) in <top (required)>'

  2) Authentication API Token Based Authentication when using a memory session store Tokens for Web Sockets gets a UI based token_ttl when requesting token for web sockets
     Failure/Error: expect(response.parsed_body["token_ttl"]).to eq(::Settings.session.timeout.to_i_with_method)
     
       expected: 3600
            got: nil
     
       (compared using ==)
     # ./spec/requests/authentication_spec.rb:371:in `block (6 levels) in <top (required)>'

  3) Authentication API Token Based Authentication when using a sql session store Tokens for Web Sockets gets a UI based token_ttl when requesting token for web sockets
     Failure/Error: expect(response.parsed_body["token_ttl"]).to eq(::Settings.session.timeout.to_i_with_method)
    
       expected: 3600
            got: nil
     
       (compared using ==)
     # ./spec/requests/authentication_spec.rb:371:in `block (6 levels) in <top (required)>'
```

**Comment by Fryguy** [comment]
Saw this just now in #1100

**Comment by NickLaMuro** [comment]
I think I was seeing that a week or two ago as well.  Might be related to a fix I had at one point:

https://github.com/ManageIQ/manageiq-api/pull/1057

**Comment by kbrock** [comment]
wonder if we want to take that code an extract into some helper methods

**Comment by Fryguy** [comment]
Duplicate of #1129
