### ISSUE TITLE
Sporadic test failure with authentication_spec

### ISSUE THREAD

**Issue by Fryguy** [ManageIQ/manageiq-api#1129]
```
$ SPEC_OPTS="--seed 32579" be rspec spec/requests/authentication_spec.rb
** Using session_store: ActionDispatch::Session::MemoryStore
** ManageIQ master, codename: Najdorf

Randomized with seed 32579
.................................F.............F............F.....

Failures:

  1) Authentication API Token Based Authentication when using a cache session store Tokens for Web Sockets gets a UI based token_ttl when requesting token for web sockets
     Failure/Error: expect(response.parsed_body["token_ttl"]).to eq(::Settings.session.timeout.to_i_with_method)

       expected: 3600
            got: nil

       (compared using ==)
     # ./spec/requests/authentication_spec.rb:371:in `block (6 levels) in <main>'
     # /Users/jfrey/.gem/ruby/2.7.4/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'

  2) Authentication API Token Based Authentication when using a sql session store Tokens for Web Sockets gets a UI based token_ttl when requesting token for web sockets
     Failure/Error: expect(response.parsed_body["token_ttl"]).to eq(::Settings.session.timeout.to_i_with_method)

       expected: 3600
            got: nil

       (compared using ==)
     # ./spec/requests/authentication_spec.rb:371:in `block (6 levels) in <main>'
     # /Users/jfrey/.gem/ruby/2.7.4/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'

  3) Authentication API Token Based Authentication when using a memory session store Tokens for Web Sockets gets a UI based token_ttl when requesting token for web sockets
     Failure/Error: expect(response.parsed_body["token_ttl"]).to eq(::Settings.session.timeout.to_i_with_method)

       expected: 3600
            got: nil

       (compared using ==)
     # ./spec/requests/authentication_spec.rb:371:in `block (6 levels) in <main>'
     # /Users/jfrey/.gem/ruby/2.7.4/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'

Finished in 18.43 seconds (files took 5.24 seconds to load)
66 examples, 3 failures

Failed examples:

rspec './spec/requests/authentication_spec.rb[1:7:3:12:1]' # Authentication API Token Based Authentication when using a cache session store Tokens for Web Sockets gets a UI based token_ttl when requesting token for web sockets
rspec './spec/requests/authentication_spec.rb[1:7:1:12:1]' # Authentication API Token Based Authentication when using a sql session store Tokens for Web Sockets gets a UI based token_ttl when requesting token for web sockets
rspec './spec/requests/authentication_spec.rb[1:7:2:12:1]' # Authentication API Token Based Authentication when using a memory session store Tokens for Web Sockets gets a UI based token_ttl when requesting token for web sockets
```

**Comment by Fryguy** [comment]
it failed at the time for this seed consistently...it's possible things have changed and we have to find a new seed.

**Comment by kbrock** [comment]
tried once, will try again. Seems like this is doing quite well right now.

```bash
for i in {1..20} ; do be rspec spec/requests/authentication_spec.rb || break ; done
```

(not sure if the `break` will successfully kick in, so just running 20 times a pop.)

**Comment by Fryguy** [comment]
Hmmm - maybe not - don't see anything in GitHub Actions.  Maybe it's fixed.

**Comment by Fryguy** [comment]
I'm gonna close - I also can't reproduce with the given seed, and I also ran it 100 times locally.

**Comment by jrafanie** [comment]
ok, so I looked at this and the only way I can see this is happening is if the return from `token_get_info` is an empty hash or a hash without token_ttl key:

https://github.com/ManageIQ/manageiq-api/blob/67eec8943039f9a76031a59d73266237e12c9723/app/controllers/api/auth_controller.rb#L9-L12

This can happen in a few scenarios:

https://github.com/ManageIQ/manageiq/blob/c2a5828bf17d7744c7ab17fe4880589184940369/lib/token_manager.rb#L41-L46

1) token_valid? is false (nil token, empty string, or not found in the token_store)
2) Note: a nil return here would cause the calling method to blow up with undefined method [] for nil, which isn't happening.  So, it's not line 44
3) reading the token is returning an empty hash {}

With this knowledge, it must be a contamination or timing issue where we're either sporadically using an invalid token for these failing examples or we read the token and it's empty.  Perhaps this is a timing problem on `ActionDispatch::Session::MemoryStore` or more likely, we're stubbing or caching the various things such as [token manager](https://github.com/ManageIQ/manageiq-api/blob/67eec8943039f9a76031a59d73266237e12c9723/lib/api/environment.rb#L33) or the [token store](https://github.com/ManageIQ/manageiq/blob/c2a5828bf17d7744c7ab17fe4880589184940369/lib/token_store.rb#L24) and some state changes are retained across tests.

I am unable to find a seed that recreates this issue so it's hard to track things down.  I do wonder if resetting the caches such as we do [in the users_spec](https://github.com/ManageIQ/manageiq-api/blob/master/spec/requests/users_spec.rb#L622-L625) would help.

**Comment by jrafanie** [comment]
Note, the prior comment is in regards to a recent failure in github actions on a cross repo.  It's important to note, it's still using memory store:

```
 ** override_gem("manageiq-ui-classic", :path=>"/home/runner/work/manageiq-cross_repo-tests/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@35401b4006f98665f75a9675e13bfff7332ab0ef") at /home/runner/work/manageiq-cross_repo-tests/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-api@0c841dcd5757445443a1bea64002fb0a2584cb7a/spec/manageiq/bundler.d/overrides.rb:1
  ** Using session_store: ActionDispatch::Session::MemoryStore
  ** ManageIQ master, codename: Oparin
  ** ManageIQ master, codename: Oparin
  ** override_gem("manageiq-ui-classic", :path=>"/home/runner/work/manageiq-cross_repo-tests/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-ui-classic@35401b4006f98665f75a9675e13bfff7332ab0ef") at /home/runner/work/manageiq-cross_repo-tests/manageiq-cross_repo-tests/repos/ManageIQ/manageiq-api@0c841dcd5757445443a1bea64002fb0a2584cb7a/spec/manageiq/bundler.d/overrides.rb:1
  ** Using session_store: ActionDispatch::Session::MemoryStore
  ** ManageIQ master, codename: Oparin
  
  Randomized with seed 19159
  Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
  Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
  .........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................F............F.............F...........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
  
  Failures:
  
    1) Authentication API Token Based Authentication when using a cache session store Tokens for Web Sockets gets a UI based token_ttl when requesting token for web sockets
       Failure/Error: expect(response.parsed_body["token_ttl"]).to eq(::Settings.session.timeout.to_i_with_method)
  
         expected: 3600
              got: nil
  
         (compared using ==)
       # ./spec/requests/authentication_spec.rb:371:in `block (6 levels) in <top (required)>'
  
    2) Authentication API Token Based Authentication when using a sql session store Tokens for Web Sockets gets a UI based token_ttl when requesting token for web sockets
       Failure/Error: expect(response.parsed_body["token_ttl"]).to eq(::Settings.session.timeout.to_i_with_method)
  
         expected: 3600
              got: nil
  
         (compared using ==)
       # ./spec/requests/authentication_spec.rb:371:in `block (6 levels) in <top (required)>'
  
    3) Authentication API Token Based Authentication when using a memory session store Tokens for Web Sockets gets a UI based token_ttl when requesting token for web sockets
       Failure/Error: expect(response.parsed_body["token_ttl"]).to eq(::Settings.session.timeout.to_i_with_method)
  
         expected: 3600
              got: nil
  
         (compared using ==)
       # ./spec/requests/authentication_spec.rb:371:in `block (6 levels) in <top (required)>'
```

**Comment by kbrock** [comment]
@jrafanie nailed it. Or at least pointed to something that I want to resolve (if not the full solution): #1171

**Comment by kbrock** [comment]
Ok, so I am diving into a different spot for this spec.
Looking at comments from Nick around why that code was introduced in the first place.

It is possible there is a nil hanging around: 
https://github.com/ManageIQ/manageiq-api/commit/e5bc44c6e9efbc72da8456a9a4aaeca10b6adddd
