### ISSUE TITLE
PhysicalChassisController - duplicate controller name

### ISSUE THREAD

**Issue by himdel** [ManageIQ/manageiq-api#489]
`PhysicalChassisController` already exists, provided by `manageiq-ui-classic/app/controllers/physical_chassis_controller.rb`.

But thanks to the API defining a controller by the same name, accessing `/physical_chassis/show_list` now fails:

```
[----] I, [2018-10-10T14:08:40.918265 #13280:2aeef94b9da4]  INFO -- : Started GET "/physical_chassis/show_list" for ::1 at 2018-10-10 14:08:40 +0000
[----] F, [2018-10-10T14:08:40.956717 #13280:2aeef94b9da4] FATAL -- :                                                                  
[----] F, [2018-10-10T14:08:40.956815 #13280:2aeef94b9da4] FATAL -- : LoadError (Unable to autoload constant PhysicalChassisController, expected /home/himdel/manageiq-api/app/controllers/api/physical_chassis_controller.rb to define it):
[----] F, [2018-10-10T14:08:40.956851 #13280:2aeef94b9da4] FATAL -- :   
[----] F, [2018-10-10T14:08:40.956894 #13280:2aeef94b9da4] FATAL -- : activesupport (5.0.7) lib/active_support/dependencies.rb:513:in `load_missing_constant'
activesupport (5.0.7) lib/active_support/dependencies.rb:203:in `const_missing'
activesupport (5.0.7) lib/active_support/inflector/methods.rb:268:in `const_get'
activesupport (5.0.7) lib/active_support/inflector/methods.rb:268:in `block in constantize'
activesupport (5.0.7) lib/active_support/inflector/methods.rb:266:in `each'
activesupport (5.0.7) lib/active_support/inflector/methods.rb:266:in `inject'
activesupport (5.0.7) lib/active_support/inflector/methods.rb:266:in `constantize'
activesupport (5.0.7) lib/active_support/dependencies.rb:584:in `get'
activesupport (5.0.7) lib/active_support/dependencies.rb:615:in `constantize'
actionpack (5.0.7) lib/action_dispatch/http/request.rb:81:in `controller_class'
actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:44:in `controller'
actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:30:in `serve'
actionpack (5.0.7) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.7) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.7) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:727:in `call'
/home/himdel/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/manageiq-graphql-5f68621f2791/lib/manageiq/graphql/rest_api_proxy.rb:18:in `call'
secure_headers (3.0.3) lib/secure_headers/middleware.rb:10:in `call'
lib/request_started_on_middleware.rb:12:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7) lib/rails/engine.rb:522:in `call'
puma (3.7.1) lib/puma/configuration.rb:232:in `call'
puma (3.7.1) lib/puma/server.rb:578:in `handle_request'
puma (3.7.1) lib/puma/server.rb:415:in `process_client'
puma (3.7.1) lib/puma/server.rb:275:in `block in run'
puma (3.7.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
[----] I, [2018-10-10T14:11:05.800290 #13280:2aeef94b9ebc]  INFO -- : Started GET "/physical_chassis/show_list" for ::1 at 2018-10-10 14:11:05 +0000
[----] D, [2018-10-10T14:11:05.830050 #13280:2aeef94b9ebc] DEBUG -- : PostgreSQLAdapter#log_after_checkout, connection_pool: size: 5, connections: 5, in use: 2, waiting_in_queue: 0
[----] D, [2018-10-10T14:11:05.830386 #13280:2aeef94b9ebc] DEBUG -- : PostgreSQLAdapter#log_after_checkout, connection_pool: size: 5, connections: 5, in use: 3, waiting_in_queue: 0
[----] D, [2018-10-10T14:11:05.830562 #13280:2aeef94b9ebc] DEBUG -- : PostgreSQLAdapter#log_after_checkout, connection_pool: size: 5, connections: 5, in use: 4, waiting_in_queue: 0
[----] D, [2018-10-10T14:11:05.830751 #13280:2aeef94b9ebc] DEBUG -- : PostgreSQLAdapter#log_after_checkout, connection_pool: size: 5, connections: 5, in use: 5, waiting_in_queue: 0
[----] D, [2018-10-10T14:11:15.831000 #13280:2aeef94b9ebc] DEBUG -- : PostgreSQLAdapter#log_after_checkin, connection_pool: size: 5, connections: 5, in use: 4, waiting_in_queue: 0
[----] D, [2018-10-10T14:11:15.831561 #13280:2aeef94b9ebc] DEBUG -- : PostgreSQLAdapter#log_after_checkin, connection_pool: size: 5, connections: 5, in use: 3, waiting_in_queue: 0
[----] D, [2018-10-10T14:11:15.832064 #13280:2aeef94b9ebc] DEBUG -- : PostgreSQLAdapter#log_after_checkin, connection_pool: size: 5, connections: 5, in use: 2, waiting_in_queue: 0
[----] D, [2018-10-10T14:11:15.832617 #13280:2aeef94b9ebc] DEBUG -- : PostgreSQLAdapter#log_after_checkin, connection_pool: size: 5, connections: 5, in use: 1, waiting_in_queue: 0
[----] D, [2018-10-10T14:11:15.833444 #13280:2aeef94b9ebc] DEBUG -- : PostgreSQLAdapter#log_after_checkin, connection_pool: size: 5, connections: 5, in use: 0, waiting_in_queue: 0
I, [2018-10-10T14:11:17.390795 #13280]  INFO -- : Initializing websocket worker!                                                       
[----] F, [2018-10-10T14:11:19.809904 #13280:2aeef94b9ebc] FATAL -- :                                                                  
[----] F, [2018-10-10T14:11:19.810036 #13280:2aeef94b9ebc] FATAL -- : LoadError (Unable to autoload constant PhysicalChassisController, expected /home/himdel/manageiq-api/app/controllers/api/physical_chassis_controller.rb to define it):
[----] F, [2018-10-10T14:11:19.810105 #13280:2aeef94b9ebc] FATAL -- :   
[----] F, [2018-10-10T14:11:19.810244 #13280:2aeef94b9ebc] FATAL -- : activesupport (5.0.7) lib/active_support/dependencies.rb:513:in `load_missing_constant'
activesupport (5.0.7) lib/active_support/dependencies.rb:203:in `const_missing'
activesupport (5.0.7) lib/active_support/inflector/methods.rb:268:in `const_get'
activesupport (5.0.7) lib/active_support/inflector/methods.rb:268:in `block in constantize'
activesupport (5.0.7) lib/active_support/inflector/methods.rb:266:in `each'
activesupport (5.0.7) lib/active_support/inflector/methods.rb:266:in `inject'
activesupport (5.0.7) lib/active_support/inflector/methods.rb:266:in `constantize'
activesupport (5.0.7) lib/active_support/dependencies.rb:584:in `get'
activesupport (5.0.7) lib/active_support/dependencies.rb:615:in `constantize'
actionpack (5.0.7) lib/action_dispatch/http/request.rb:81:in `controller_class'
actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:44:in `controller'
actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:30:in `serve'
actionpack (5.0.7) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.7) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.7) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.7) lib/action_dispatch/routing/route_set.rb:727:in `call'
/home/himdel/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/bundler/gems/manageiq-graphql-5f68621f2791/lib/manageiq/graphql/rest_api_proxy.rb:18:in `call'
secure_headers (3.0.3) lib/secure_headers/middleware.rb:10:in `call'
lib/request_started_on_middleware.rb:12:in `call'
rack (2.0.5) lib/rack/etag.rb:25:in `call'
rack (2.0.5) lib/rack/conditional_get.rb:25:in `call'
rack (2.0.5) lib/rack/head.rb:12:in `call'
rack (2.0.5) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.5) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/cookies.rb:613:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.0.7) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.7) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.5) lib/rack/method_override.rb:22:in `call'
rack (2.0.5) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
railties (5.0.7) lib/rails/engine.rb:522:in `call'
puma (3.7.1) lib/puma/configuration.rb:232:in `call'
puma (3.7.1) lib/puma/server.rb:578:in `handle_request'
puma (3.7.1) lib/puma/server.rb:415:in `process_client'
puma (3.7.1) lib/puma/server.rb:275:in `block in run'
puma (3.7.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```

**Comment by himdel** [comment]
The controller is actually namespaced right... so, possibly the culprit is something in graphql.

Not sure what that's doing there or why it gets called though.

**Comment by thearifismail** [comment]
Could not reproduce the problem when using master stream and no bundler.d/overrides.rb used.  
<img width="1434" alt="physical_chassis" src="https://user-images.githubusercontent.com/40067075/55256710-1a07b300-5234-11e9-9270-63ff24bbccff.png">

Could reproduce the problem when "bundler.d/overrides.rb" was used to load "manageiq-api".

**Comment by jrafanie** [comment]
@thearifismail asked me to take a look at this... I can't recreate this.  I can envision the only way this can occur:

```
irb(main):002:0> pp $LOAD_PATH.grep(/controllers/)
["/Users/joerafaniello/.gem/ruby/2.4.5/bundler/gems/manageiq-v2v-63d961599bea/app/controllers",
 "/Users/joerafaniello/.gem/ruby/2.4.5/bundler/gems/manageiq-ui-classic-01c014825f79/app/controllers/mixins",
 "/Users/joerafaniello/.gem/ruby/2.4.5/bundler/gems/manageiq-ui-classic-01c014825f79/app/controllers",
 "/Users/joerafaniello/.gem/ruby/2.4.5/gems/high_voltage-3.0.0/app/controllers",
 "/Users/joerafaniello/.gem/ruby/2.4.5/gems/high_voltage-3.0.0/app/controllers/concerns",
 "/Users/joerafaniello/.gem/ruby/2.4.5/bundler/gems/manageiq-graphql-82fdd9385bdd/app/controllers",
 "/Users/joerafaniello/.gem/ruby/2.4.5/bundler/gems/manageiq-api-55621be8daa6/app/controllers/api",
 "/Users/joerafaniello/.gem/ruby/2.4.5/bundler/gems/manageiq-api-55621be8daa6/app/controllers"]
```

Something tries to autoload the constant `PhysicalChassisController` using the ` "/Users/joerafaniello/.gem/ruby/2.4.5/bundler/gems/manageiq-api-55621be8daa6/app/controllers/api"` from the load path.  The constant defined by that file is `Api:: PhysicalChassisController`.  I tried dropping the other controller paths from the load path and couldn't recreate it so I have something wrong.

Does this only happen in dev mode?  Maybe it's not code reloading friendly?

**Comment by jrafanie** [comment]
@himdel ^

**Comment by thearifismail** [comment]
To see if the problem was caused by overriding just the `manageiq-api` or other plugins also, I used `manageiq-graphql` and removed `manageiq-api` from the `bundler.d/overrides.rb`.  The problem went away.  It appears that the problem occurs only in dev mode and is limited to `manageiq-api`.

**Comment by himdel** [comment]
@jrafanie I'm not quite sure if it's *limited* to dev mode or just less likely to appear otherwise, but for me, the surest way to recreate the issue in cases it went away was to simply `touch manageiq-api/app/controllers/api/physical_chassis_controller.rb`.

So, yeah, I'm guessing autoloader issues..

**Comment by thearifismail** [comment]
@jrafanie Here are the steps to reproduce the problem:

1.  `git clone git@github.com:ManageIQ/manageiq.git`
2.  Run the server using `bin/rails s`
3.  Using rails console, add a couple of physical chasses using 
`chassis = ManageIQ::Providers::Redfish::PhysicalInfraManager::PhysicalChassis.new( :name => "my_redfish_chassis")`
`chassis.save!`
`chassis = ManageIQ::Providers::Lenovo::PhysicalInfraManager::PhysicalChassis.new( :name => "my_lenovo_chassis")`
`chassis.save!` 
3.  Log into MiQ and hit `http://localhost:3000/physical_chassis` and it should load the two chasses just created.
4.  Stop ManageIQ.
4. `git clone git@github.com:ManageIQ/manageiq-api.git`
5.  create file `<mangeiq_dir>/bundler.d/overrides.rb`
6.  To override, the default manageiq-api, add to the `overrides.rb` `override_gem "manageiq-api", :path => "<PATH_TO _THE_PARENT_DIR>/manageiq-api`
7.  Start ManageIQ, login and hit `http://localhost:3000/physical_chassis`
PROBLEM: Page not found and the development log should show the FATAL errors reported in the original description.

**Comment by Fryguy** [comment]
Hugh step back but why is controllers/api on the load path? That alone feels like recipe for disaster, because it effectively unnamespaces from autoloads point of view

**Comment by tadeboro** [comment]
I can replicate the error by performing the following steps:

 1. Checkout latest master branch of `manageiq` core repo.
 2. Remove all overrides from `bundler.d`.
 3. Run `bin/update`.
 4. Add `override_gem "manageiq-api", :path => "/path/to/manageiq-api` to overrides, where `/path/to/manageiq-api` repo has checked-out latest master.
 5. Visit http://localhost:3000/physical_chassis/show_list

If I remove the override, the error is gone.

**Comment by jrafanie** [comment]
> Hugh step back but why is controllers/api on the load path? That alone feels like recipe for disaster, because it effectively unnamespaces from autoloads point of view

Good point.  I believe I tried removing the controllers/api from the autoload path at some point and it was a disaster.  It's probably the best thing to do even if it's breaks everywhere.  I'll see if I can dig up the problems I encountered when I did that.

**Comment by Fryguy** [comment]
Taking it a step further, when you put a directory on the autoloads path, that implies the directory name is not in the namespace (e.g. we don't have Mixins::PasswordMixin).  The fact that Api:: is a thing should preclude it from being on the autoload path

**Comment by Fryguy** [comment]
I think this can be closed now that the autoload_path no longer contains manageiq-api/app/controllers/api.

If anyone can reproduce on the latest code, please feel free to reopen,

**Comment by himdel** [comment]
:+1: I just retried https://github.com/ManageIQ/manageiq-api/issues/489#issuecomment-479248848 and I can't reprodue anymore :)
