### ISSUE TITLE
Server error (500) returned after editing Catalog item with used name

### ISSUE THREAD

**Issue by rvsia** [ManageIQ/manageiq-api#574]
`Services > Catalogs > Catalogs > Configuration > New/Edit`

**Description**
- When you add a new Catalog with used name it returns 400 error
- However when you edit some Catalog and change its name to used name **it returns 500 error**

`http://localhost:3000/api/service_catalogs/45`

**body**

```
{
  "action": "edit",
  "resource": {
    "name": "Aa" // something what is already used
  }
}
```

**response**

500 Interval Server Error

```
{
"error": {
   "kind": "internal_server_error",
    "message": "Validation failed: ServiceTemplateCatalog: Name has already been taken",
    "klass": "ActiveRecord::RecordInvalid"
    }
}
```

**Comment by himdel** [comment]
```
[----] I, [2019-04-12T14:07:20.098134 #16433:2b26bc2d126c]  INFO -- : MIQ(Api::ServiceCatalogsController.log_request_initiated)  
[----] I, [2019-04-12T14:07:20.098252 #16433:2b26bc2d126c]  INFO -- : MIQ(Api::ServiceCatalogsController.log_request) API Request:    {:requested_at=>"2019-04-12 14:07:20 UTC", :method=>"POST", :url=>"http://localhost:3000/api/service_catalogs/1"}
[----] I, [2019-04-12T14:07:20.192356 #16433:2b26bc2d126c]  INFO -- : MIQ(Api::ServiceCatalogsController.log_request) Authentication: {:type=>"basic", :token=>nil, :x_miq_group=>nil, :user=>"admin"}
[----] I, [2019-04-12T14:07:20.205885 #16433:2b26bc2d126c]  INFO -- : MIQ(Api::ServiceCatalogsController.log_request) Authorization:  {:user=>"admin", :group=>"EvmGroup-super_administrator", :role=>"EvmRole-super_administrator", :tenant=>"My Company"}
[----] I, [2019-04-12T14:07:20.211355 #16433:2b26bc2d126c]  INFO -- : MIQ(Api::ServiceCatalogsController.log_request) Request:        {:method=>:post, :action=>"edit", :fullpath=>"/api/service_catalogs/1", :url=>"http://localhost:3000/api/service_catalogs/1", :base=>"http://localhost:3000", :path=>"/api/service_catalogs/1", :prefix=>"/api", :version=>"4.1.0-pre", :api_prefix=>"http://localhost:3000/api", :collection=>"service_catalogs", :c_suffix=>nil, :collection_id=>"1", :subcollection=>nil, :subcollection_id=>nil}
[----] I, [2019-04-12T14:07:20.212252 #16433:2b26bc2d126c]  INFO -- : MIQ(Api::ServiceCatalogsController.log_request) Parameters:     {"action"=>"update", "controller"=>"api/service_catalogs", "format"=>"json", "body"=>{"action"=>"edit", "resource"=>{"name"=>"Single Service"}}}
[----] E, [2019-04-12T14:07:20.240266 #16433:2b26bc2d126c] ERROR -- : MIQ(Api::ServiceCatalogsController.api_error) ActiveRecord::RecordInvalid: Validation failed: ServiceTemplateCatalog: Name has already been taken
[----] E, [2019-04-12T14:07:20.240397 #16433:2b26bc2d126c] ERROR -- : MIQ(Api::ServiceCatalogsController.api_error) 

/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/validations.rb:78:in `raise_validation_error'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/validations.rb:50:in `save!'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/attribute_methods/dirty.rb:30:in `save!'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:324:in `block in save!'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:211:in `transaction'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:324:in `save!'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/suppressor.rb:45:in `save!'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/persistence.rb:288:in `block in update!'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:211:in `transaction'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/persistence.rb:286:in `update!'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/manageiq-api-9240a6cb1e59/app/controllers/api/base_controller/generic.rb:53:in `edit_resource'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/manageiq-api-9240a6cb1e59/app/controllers/api/base_controller/manager.rb:105:in `update_one_collection'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/manageiq-api-9240a6cb1e59/app/controllers/api/base_controller/manager.rb:92:in `get_and_update_one_collection'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/manageiq-api-9240a6cb1e59/app/controllers/api/base_controller/manager.rb:15:in `update_collection'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/manageiq-api-9240a6cb1e59/app/controllers/api/base_controller.rb:94:in `update'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/abstract_controller/base.rb:188:in `process_action'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:126:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:455:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_controller/metal/rescue.rb:20:in `process_action'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:164:in `block in instrument'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/notifications.rb:164:in `instrument'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-5.0.7.2/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/abstract_controller/base.rb:126:in `process'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_controller/metal.rb:190:in `dispatch'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_controller/metal.rb:262:in `dispatch'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/journey/router.rb:39:in `block in serve'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/journey/router.rb:26:in `each'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/journey/router.rb:26:in `serve'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/routing/route_set.rb:727:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/manageiq-graphql-38bd898e7eb3/lib/manageiq/graphql/rest_api_proxy.rb:18:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/secure_headers-3.0.3/lib/secure_headers/middleware.rb:10:in `call'
/home/himdel/manageiq/lib/request_started_on_middleware.rb:12:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.0.7.2/lib/rails/rack/logger.rb:36:in `call_app'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.0.7.2/lib/rails/rack/logger.rb:26:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/request_id.rb:24:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activesupport-5.0.7.2/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/actionpack-5.0.7.2/lib/action_dispatch/middleware/static.rb:136:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/railties-5.0.7.2/lib/rails/engine.rb:522:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.7.1/lib/puma/configuration.rb:232:in `call'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.7.1/lib/puma/server.rb:578:in `handle_request'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.7.1/lib/puma/server.rb:415:in `process_client'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.7.1/lib/puma/server.rb:275:in `block in run'
/home/himdel/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/puma-3.7.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
[----] I, [2019-04-12T14:07:20.242441 #16433:2b26bc2d126c]  INFO -- : MIQ(Api::ServiceCatalogsController.log_request) Response:       {:completed_at=>"2019-04-12 14:07:20 UTC", :size=>"0.163 KBytes", :time_taken=>"0.144 Seconds", :status=>500}
```

**Comment by h-kataria** [comment]
was not able to recreate issue in UI, seems like this issue was addressed in UI with form conversion to react in https://github.com/ManageIQ/manageiq-ui-classic/pull/5139

@martinpovolny do we need to fix something on API side for this?

**Comment by h-kataria** [comment]
@miq-bot assign @martinpovolny

**Comment by martinpovolny** [comment]
This is consistent with other places. For example:

````
lucifer ruby-2.5.5 - [~/Projects/manageiq-api] (master)$ echo '{ "action": "edit", "resource": { "name": "Loic" } }' | api post roles/20

{
  "error": {
    "kind": "internal_server_error",
    "message": "Validation failed: MiqUserRole: Name has already been taken",
    "klass": "ActiveRecord::RecordInvalid"
  }
}
````

We probably should have a better generic way of handling this.

I am not sure, but maybe the right HTTP code to return would be "422 Unprocessable Entity".

Also the validation error should probably be better structured so that the UI can present it to the user and possibly a translation in the current locale shoud be returned.

Thoughts on this one? @rvsia, @himdel, @abellotti ?

**Comment by himdel** [comment]
:+1:, but looks like we're using 400 in other places.

As for i18n vs the error message, maybe we should use a similar mechanism as notifications (`miqFormatNotification`) - serve a translatable format string and the parameters separately?
(Not sure if the API should be able to tell the current language.)

**Comment by Fryguy** [comment]
@abellotti Can you verify?

**Comment by abellotti** [comment]
This is still an issue,  we should handle these generically and return a 400 like we do with other ActiveRecord exceptions. I'll create a PR.
