### ISSUE TITLE
API returns InternalServerError when setting the offset greater than the count (for non admin users)

### ISSUE THREAD

**Issue by evertmulder** [ManageIQ/manageiq-api#710]
API returns an 500 InternalServerError when an API call is made the offset parameter is filled with an value greater the the returned collection. This does not happen when using an super admin account.

# Steps to reproduce 
```
# Run as user
 curl -u username:password "http://manageiq/api/vms?offset=21"

# this returns
{"error":{"kind":"internal_server_error","message":"undefined method `count' for nil:NilClass","klass":"NoMethodError"}}

# Running as admin, no error
 curl -u admin:smartvm "http://manageiq.manageiq-test.svc/api/vms?offset=1000"
{"name":"vms","count":227,"subcount":0,"pages":1,"resources":[],"actions":[{"name":"query","method":"post","href":"http://localhost:4000/api/vms"},{"name":"edit","method":"post","href":"http://localhost:4000/api/vms"},{"name":"add_lifecycle_event","method":"post","href":"http://localhost:4000/api/vms"},{"name":"add_event","method":"post","href":"http://localhost:4000/api/vms"},{"name":"refresh","method":"post","href":"http://localhost:4000/api/vms"},{"name":"shutdown_guest","method":"post","href":"http://localhost:4000/api/vms"},{"name":"reboot_guest","method":"post","href":"http://localhost:4000/api/vms"},{"name":"start","method":"post","href":"http://localhost:4000/api/vms"},{"name":"stop","method":"post","href":"http://localhost:4000/api/vms"},{"name":"suspend","method":"post","href":"http://localhost:4000/api/vms"},{"name":"shelve","method":"post","href":"http://localhost:4000/api/vms"},{"name":"shelve_offload","method":"post","href":"http://localhost:4000/api/vms"},{"name":"pause","method":"post","href":"http://localhost:4000/api/vms"},{"name":"request_console","method":"post","href":"http://localhost:4000/api/vms"},{"name":"reset","method":"post","href":"http://localhost:4000/api/vms"},{"name":"retire","method":"post","href":"http://localhost:4000/api/vms"},{"name":"request_retire","method":"post","href":"http://localhost:4000/api/vms"},{"name":"set_owner","method":"post","href":"http://localhost:4000/api/vms"},{"name":"set_ownership","method":"post","href":"http://localhost:4000/api/vms"},{"name":"set_miq_server","method":"post","href":"http://localhost:4000/api/vms"},{"name":"scan","method":"post","href":"http://localhost:4000/api/vms"},{"name":"delete","method":"post","href":"http://localhost:4000/api/vms"},{"name":"assign_tags","method":"post","href":"http://localhost:4000/api/vms"},{"name":"unassign_tags","method":"post","href":"http://localhost:4000/api/vms"}],"links":{"self":"http://localhost:4000/api/vms?offset=1000","previous":"http://localhost:4000/api/vms?offset=0","first":"http://localhost:4000/api/vms?offset=0","last":"http://localhost:4000/api/vms?offset=0"}}
```
From the api.log
```
[----] I, [2019-11-15T14:40:05.200650 #213:499d3ac]  INFO -- : MIQ(Api::VmsController.log_request) API Request: {:requested_at=>"2019-11-15 14:40:05 UTC", :method=>"GET", :url=>"http://localhost:4000/api/vms?offset=21"}
[----] I, [2019-11-15T14:40:06.058564 #213:499d3ac]  INFO -- : MIQ(Api::VmsController.log_request) Authentication: {:type=>"basic", :token=>nil, :x_miq_group=>nil, :user=>"dalen451@support.local"}
[----] I, [2019-11-15T14:40:06.074370 #213:499d3ac]  INFO -- : MIQ(Api::VmsController.log_request) Authorization: {:user=>"dalen451@support.local", :group=>"ResourceUsers_ViperNext_Tenant_DI9_KeyUser", :role=>"ViperNextRole-keyuser", :tenant=>"DI9"}
[----] I, [2019-11-15T14:40:06.075019 #213:499d3ac]  INFO -- : MIQ(Api::VmsController.log_request) Request: {:method=>:get, :action=>"read", :fullpath=>"/api/vms?offset=21", :url=>"http://localhost:4000/api/vms?offset=21", :base=>"http://localhost:4000", :path=>"/api/vms", :prefix=>"/api", :version=>"4.1.0", :api_prefix=>"http://localhost:4000/api", :collection=>"vms", :c_suffix=>nil, :collection_id=>nil, :subcollection=>nil, :subcollection_id=>nil}
[----] I, [2019-11-15T14:40:06.075487 #213:499d3ac]  INFO -- : MIQ(Api::VmsController.log_request) Parameters: {"offset"=>"21", "action"=>"index", "controller"=>"api/vms", "format"=>"json", "body"=>{}}
[----] E, [2019-11-15T14:40:06.461864 #213:499d3ac] ERROR -- : MIQ(Api::VmsController.api_error) NoMethodError: undefined method `count' for nil:NilClass
[----] E, [2019-11-15T14:40:06.462278 #213:499d3ac] ERROR -- : MIQ(Api::VmsController.api_error)
/usr/local/lib/ruby/gems/2.5.0/bundler/gems/manageiq-api-006d816cf2a0/app/controllers/api/base_controller.rb:55:in `index'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:186:in `process_action'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:131:in `run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/abstract_controller/callbacks.rb:19:in `process_action'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal/rescue.rb:20:in `process_action'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `block in instrument'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal/params_wrapper.rb:252:in `process_action'
/usr/local/lib/ruby/gems/2.5.0/gems/activerecord-5.1.7/lib/active_record/railties/controller_runtime.rb:22:in `process_action'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/abstract_controller/base.rb:124:in `process'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal.rb:189:in `dispatch'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_controller/metal.rb:253:in `dispatch'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:31:in `serve'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:50:in `block in serve'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `each'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/journey/router.rb:33:in `serve'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/routing/route_set.rb:844:in `call'
/usr/local/lib/ruby/gems/2.5.0/bundler/gems/manageiq-graphql-ef6880aaae05/lib/manageiq/graphql/rest_api_proxy.rb:18:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/secure_headers-3.0.3/lib/secure_headers/middleware.rb:10:in `call'
/var/www/miq/vmdb/lib/request_started_on_middleware.rb:12:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:25:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/callbacks.rb:97:in `run_callbacks'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/callbacks.rb:24:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:36:in `call_app'
/usr/local/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/rack/logger.rb:26:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/activesupport-5.1.7/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/actionpack-5.1.7/lib/action_dispatch/middleware/executor.rb:12:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/railties-5.1.7/lib/rails/engine.rb:522:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/puma-3.7.1/lib/puma/configuration.rb:232:in `call'
/usr/local/lib/ruby/gems/2.5.0/gems/puma-3.7.1/lib/puma/server.rb:578:in `handle_request'
/usr/local/lib/ruby/gems/2.5.0/gems/puma-3.7.1/lib/puma/server.rb:415:in `process_client'
/usr/local/lib/ruby/gems/2.5.0/gems/puma-3.7.1/lib/puma/server.rb:275:in `block in run'
/usr/local/lib/ruby/gems/2.5.0/gems/puma-3.7.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'
[----] I, [2019-11-15T14:40:06.462787 #213:499d3ac]  INFO -- : MIQ(Api::VmsController.log_request) Response:
{:completed_at=>"2019-11-15 14:40:06 UTC", :size=>"0.120 KBytes", :time_taken=>"1.262 Seconds", :status=>500}  
```

Using Ivanchuk-1

**Comment by martinpovolny** [comment]
the root cause here goes after `Rbac.filtered` behaving inconsistently:

`
Rbac.filtered(res, {:user => User.current_user, :offset=>"9999", :limit=>1000})
=> nil
`

vs

`
Rbac.filtered(res, {:user => User.current_user})
[]
`

Anyway we can handle this on the API side.
