### ISSUE TITLE
Service request_retire action is missing the retirement in future capability

### ISSUE THREAD

**Issue by abellotti** [ManageIQ/manageiq-api#817]
The new request_retire action for service is missing the retirement in the future via the "_date_" and "_warn_" parameters as per: https://www.manageiq.org/docs/reference/latest/api/reference/services#service-retiring-future

**Comment by d-m-u** [comment]
hey @abellotti we talked about making this logic generic but I don't think that works, I think it needs to be separate: 

if you change the generic method to be
```def request_retire_resource(type, id, data = nil)
        klass = collection_class(type)
        if id
          msg = "#{User.current_user.userid} retiring #{type} id #{id} as a request"
          resource = resource_search(id, type, klass)
          api_log_info(msg)

          if data && data["date"]
            opts = {}
            opts[:date] = data["date"]
            opts[:warn] = data["warn"] if data["warn"]
            msg << " on: #{opts}"
            api_log_info(msg)
            resource.retire(opts)
          else
            msg << " immediately."
            api_log_info(msg)
             klass.make_retire_request(resource.id, User.current_user)
          end

        else
          raise BadRequestError, "Must specify an id for retiring a #{type} resource"
        end
      end``` 

and comment out the vm method of the same name and then run a retire_request on a vm you'll hit this:

```Error caught: [NoMethodError] undefined method `keys' for #<Array:0x00007fed30767af8>
/Users/drewmu/manageiq-api/app/controllers/api/base_controller/normalizer.rb:126:in `normalize_select_attributes'
/Users/drewmu/manageiq-api/app/controllers/api/base_controller/normalizer.rb:11:in `normalize_hash'
/Users/drewmu/manageiq-api/app/controllers/api/base_controller/renderer.rb:80:in `resource_to_jbuilder' ...```

because, inside the base_controller/manager, we do this: 

```
def update_one_collection(is_subcollection, target, type, id, resource)
        id = id.to_i if id =~ /\A\d+\z/
        parent_resource = parent_resource_obj if is_subcollection
        if is_subcollection
          send(target, parent_resource, type, id, resource)
        else
          t = send(target, type, id, resource)
                    $api_log.info("update_one_collection 1 with #{t}")
          t
        end
      end
```

it'll log `update_one_collection 1 with #<ServiceRetireRequest:0x00007fed376fe8f8>` for a service retire request (which is perfect) but for a vm retire request I get `update_one_collection 1 with [#<ManageIQ::Providers::Vmware::InfraManager::Vm id: 4631, vendor: "vmware", format: nil, version: nil, name: "vm_name.test", description: nil...` which will then break inside the normalizer.
