### ISSUE TITLE
[NoMethodError] undefined method `lookup_by_identity' for nil:NilClass

### ISSUE THREAD

**Issue by agrare** [ManageIQ/manageiq-api#894]
Testing with multi-tenancy and hit this error on the UI:
```
[----] I, [2020-09-21T17:45:37.926357 #153867:b5734]  INFO -- : Started GET "/ws/notifications/" [WebSocket] for ::1 at 2020-09-21 17:45:37 -0400
[----] I, [2020-09-21T17:45:37.926687 #153867:b5734]  INFO -- : Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: keep-alive, Upgrade, HTTP_UPGRADE: websocket)
[----] D, [2020-09-21T17:45:37.947969 #153867:b5888] DEBUG -- : Cache read: 527ab26e860cc2aab1ceb21b442ad330
[----] D, [2020-09-21T17:45:37.948251 #153867:b5888] DEBUG -- : Dalli::Server#connect 127.0.0.1:11211
[----] D, [2020-09-21T17:45:37.948647 #153867:b5888] DEBUG -- : Cache read: 527ab26e860cc2aab1ceb21b442ad330
[----] D, [2020-09-21T17:45:37.949035 #153867:b5888] DEBUG -- : PostgreSQLAdapter#log_after_checkout, connection_pool: size: 5, connections: 1, in use: 1, waiting_in_queue: 0
[----] D, [2020-09-21T17:45:37.951573 #153867:b5888] DEBUG -- :   User Load (1.7ms)  SELECT  "users".* FROM "users" WHERE "users"."userid" = $1 LIMIT $2  [["userid", "coke"], ["LIMIT", 1]]
[----] D, [2020-09-21T17:45:38.040820 #153867:b5888] DEBUG -- :   User Inst Including Associations (0.2ms - 1rows)
[----] I, [2020-09-21T17:45:38.041780 #153867:b5888]  INFO -- : Registered connection (Z2lkOi8vdm1kYi9Vc2VyLzI)
[----] F, [2020-09-21T17:45:38.041076 #153867:b575c] FATAL -- : Error caught: [NoMethodError] undefined method `lookup_by_identity' for nil:NilClass
/home/grare/adam/src/manageiq/manageiq/app/models/user.rb:217:in `lookup_by_identity'
/home/grare/adam/.gems/2.7.0/bundler/gems/manageiq-api-6a81d6245838/app/controllers/api/base_controller/authentication.rb:91:in `auth_user'
/home/grare/adam/.gems/2.7.0/bundler/gems/manageiq-api-6a81d6245838/app/controllers/api/base_controller/authentication.rb:40:in `require_api_user_or_token'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:426:in `block in make_lambda'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:179:in `block (2 levels) in halting_and_conditional'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:180:in `block in halting_and_conditional'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `block in invoke_before'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `each'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:513:in `invoke_before'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:131:in `run_callbacks'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/abstract_controller/callbacks.rb:41:in `process_action'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/rescue.rb:22:in `process_action'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `block in instrument'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/notifications.rb:168:in `instrument'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/home/grare/adam/.gems/2.7.0/gems/activerecord-5.2.4.4/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/abstract_controller/base.rb:134:in `process'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_controller/metal.rb:191:in `dispatch'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_controller/metal.rb:252:in `dispatch'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:35:in `each'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/journey/router.rb:35:in `serve'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/routing/route_set.rb:840:in `call'
/home/grare/adam/src/manageiq/manageiq/lib/request_started_on_middleware.rb:12:in `call'
/home/grare/adam/.gems/2.7.0/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
/home/grare/adam/.gems/2.7.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
/home/grare/adam/.gems/2.7.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:27:in `call'
/home/grare/adam/.gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/home/grare/adam/.gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
/home/grare/adam/.gems/2.7.0/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/callbacks.rb:98:in `run_callbacks'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/home/grare/adam/.gems/2.7.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:38:in `call_app'
/home/grare/adam/.gems/2.7.0/gems/railties-5.2.4.4/lib/rails/rack/logger.rb:28:in `call'
/home/grare/adam/.gems/2.7.0/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/home/grare/adam/.gems/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
/home/grare/adam/.gems/2.7.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
/home/grare/adam/.gems/2.7.0/gems/activesupport-5.2.4.4/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/executor.rb:14:in `call'
/home/grare/adam/.gems/2.7.0/gems/actionpack-5.2.4.4/lib/action_dispatch/middleware/static.rb:127:in `call'
/home/grare/adam/.gems/2.7.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
/home/grare/adam/.gems/2.7.0/gems/secure_headers-3.9.0/lib/secure_headers/middleware.rb:12:in `call'
/home/grare/adam/.gems/2.7.0/gems/railties-5.2.4.4/lib/rails/engine.rb:524:in `call'
/home/grare/adam/.gems/2.7.0/gems/puma-4.3.6/lib/puma/configuration.rb:228:in `call'
/home/grare/adam/.gems/2.7.0/gems/puma-4.3.6/lib/puma/server.rb:713:in `handle_request'
/home/grare/adam/.gems/2.7.0/gems/puma-4.3.6/lib/puma/server.rb:472:in `process_client'
/home/grare/adam/.gems/2.7.0/gems/puma-4.3.6/lib/puma/server.rb:328:in `block in run'
/home/grare/adam/.gems/2.7.0/gems/puma-4.3.6/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

**Comment by jvlcek** [comment]
In chatting with @agrare it seems the configuration he had setup where this issue was encountered was:

Stand up a single instance of MiQ
Create 2 tenants, Coke and Pepsi
Create 1 users, coke, using database authentication in the Coke tenant
Create 1 users, pepsi, using database authentication in the Pepsi tenant
Configure an EMS in the Coke tenant by adding the Amazon provider in the Coke tenant.
Configure an EMS in the Pepsi tenant by adding the Amazon provider in the Pepsi tenant.
Then  attempt to log in as the coke or pepsi user.

@agrare Please let me know if I have this correct. 

Thanks! JoeV
